export interface EraVisualTheme {
  era: number;
  name: string;
  subtitle: string;
  skyGradient: string;
  groundColor: string;
  pathColor: string;
  accentColor: string;
  sceneryType: 'primitive' | 'ancient' | 'antiquity' | 'norman' | 'medieval' | 'renaissance' | 'industrial' | 'modern' | 'cyber' | 'space';
  enemyName: string;
  enemyRole: string;
  enemyIcon: string;
  enemyColor: string;
  enemyBg: string;
  decorations: string[];
}

export const ERA_THEMES: Record<number, EraVisualTheme> = {
  1: {
    era: 1,
    name: 'Primitive Wilderness',
    subtitle: 'Prehistoric Savannah & Volcanic Ridge',
    skyGradient: 'from-amber-950 via-emerald-950/80 to-stone-950',
    groundColor: '#192617',
    pathColor: '#4a3325',
    accentColor: '#f97316',
    sceneryType: 'primitive',
    enemyName: 'Sabertooth Behemoth',
    enemyRole: 'Apex Alpha Beast',
    enemyIcon: 'Bone',
    enemyColor: '#f97316',
    enemyBg: 'from-amber-950/80 to-stone-900',
    decorations: ['🪨', '🌿', '🪵', '🔥', '🦴'],
  },
  2: {
    era: 2,
    name: 'Ancient Oasis',
    subtitle: 'Golden Pyramids & Pharaoh Dunes',
    skyGradient: 'from-amber-900 via-orange-950 to-stone-950',
    groundColor: '#382210',
    pathColor: '#96703b',
    accentColor: '#38bdf8',
    sceneryType: 'ancient',
    enemyName: 'Anubis Tomb Guard',
    enemyRole: 'Desert Mummy Sentinel',
    enemyIcon: 'Sparkles',
    enemyColor: '#38bdf8',
    enemyBg: 'from-sky-950/80 to-amber-950/60',
    decorations: ['🌴', '🏺', '🏛️', '🐪', '☀️'],
  },
  3: {
    era: 3,
    name: 'Greco-Roman Camp',
    subtitle: 'Colosseum Colonnade & Legion Highway',
    skyGradient: 'from-teal-950 via-slate-900 to-emerald-950/70',
    groundColor: '#1a3320',
    pathColor: '#b0a68f',
    accentColor: '#22c55e',
    sceneryType: 'antiquity',
    enemyName: 'Centurion Gladiator',
    enemyRole: 'Arena Champion',
    enemyIcon: 'Shield',
    enemyColor: '#22c55e',
    enemyBg: 'from-emerald-950/80 to-stone-900',
    decorations: ['🌲', '🎪', '🎯', '🐎', '🛡️'],
  },
  4: {
    era: 4,
    name: 'Norman Fjords',
    subtitle: 'Aurora Borealis & Viking Longhouses',
    skyGradient: 'from-slate-950 via-cyan-950/80 to-blue-950',
    groundColor: '#172338',
    pathColor: '#526077',
    accentColor: '#38bdf8',
    sceneryType: 'norman',
    enemyName: 'Viking Frost Berserker',
    enemyRole: 'Fjord War-Chieftain',
    enemyIcon: 'Crown',
    enemyColor: '#eab308',
    enemyBg: 'from-yellow-950/80 to-slate-900',
    decorations: ['🌲', '❄️', '🛖', '🪓', '🐺'],
  },
  5: {
    era: 5,
    name: 'Medieval Fortress',
    subtitle: 'Royal Citadel Battlements & Torches',
    skyGradient: 'from-purple-950 via-slate-900 to-zinc-950',
    groundColor: '#251c30',
    pathColor: '#52525b',
    accentColor: '#ec4899',
    sceneryType: 'medieval',
    enemyName: 'Black Knight Dreadlord',
    enemyRole: 'Fortress Warlord',
    enemyIcon: 'Sword',
    enemyColor: '#ec4899',
    enemyBg: 'from-pink-950/80 to-purple-950/80',
    decorations: ['🏰', '🚩', '⚔️', '🛡️', '🐎'],
  },
  6: {
    era: 6,
    name: 'Renaissance Piazza',
    subtitle: 'Grand Venetian Palaces & Piazza Mosaics',
    skyGradient: 'from-fuchsia-950 via-purple-950 to-slate-950',
    groundColor: '#2d1838',
    pathColor: '#b89a77',
    accentColor: '#c084fc',
    sceneryType: 'renaissance',
    enemyName: 'Duelist Maestro',
    enemyRole: 'Master Blade Musketeer',
    enemyIcon: 'Feather',
    enemyColor: '#c084fc',
    enemyBg: 'from-purple-950/80 to-stone-900',
    decorations: ['🏛️', '🎭', '🌹', '🕯️', '🎨'],
  },
  7: {
    era: 7,
    name: 'Industrial Foundry',
    subtitle: 'Molten Steamworks & Iron Smokestacks',
    skyGradient: 'from-amber-950 via-stone-900 to-zinc-950',
    groundColor: '#241b14',
    pathColor: '#475569',
    accentColor: '#06b6d4',
    sceneryType: 'industrial',
    enemyName: 'Clockwork Steam Titan',
    enemyRole: 'Foundry Automaton',
    enemyIcon: 'Cog',
    enemyColor: '#06b6d4',
    enemyBg: 'from-cyan-950/80 to-zinc-900',
    decorations: ['🏭', '⚙️', '💨', '🚂', '🔩'],
  },
  8: {
    era: 8,
    name: 'Modern Warfront',
    subtitle: 'Midnight Warfront & Sky Searchlights',
    skyGradient: 'from-blue-950 via-slate-950 to-indigo-950',
    groundColor: '#131b2c',
    pathColor: '#334155',
    accentColor: '#6366f1',
    sceneryType: 'modern',
    enemyName: 'Cyber Mech Commander',
    enemyRole: 'Spec-Ops Vanguard',
    enemyIcon: 'Crosshair',
    enemyColor: '#6366f1',
    enemyBg: 'from-indigo-950/80 to-slate-950',
    decorations: ['🏢', '🚁', '🚧', '💥', '🛰️'],
  },
  9: {
    era: 9,
    name: 'Digital Matrix',
    subtitle: 'Holographic Cyber City & Data Grid',
    skyGradient: 'from-violet-950 via-zinc-950 to-orange-950/60',
    groundColor: '#120b22',
    pathColor: '#c2410c',
    accentColor: '#f97316',
    sceneryType: 'cyber',
    enemyName: 'Neural AI Sovereign',
    enemyRole: 'Synthetic Overlord',
    enemyIcon: 'Cpu',
    enemyColor: '#f97316',
    enemyBg: 'from-orange-950/80 to-purple-950/90',
    decorations: ['⚡', '💾', '🌐', '📡', '💠'],
  },
  10: {
    era: 10,
    name: 'Cosmic Stellar Orbit',
    subtitle: 'Singularity Void & Celestial Rings',
    skyGradient: 'from-purple-950 via-black to-fuchsia-950',
    groundColor: '#0c071a',
    pathColor: '#7e22ce',
    accentColor: '#d946ef',
    sceneryType: 'space',
    enemyName: 'Void Celestial God',
    enemyRole: 'Cosmic Singularity Harbinger',
    enemyIcon: 'Globe',
    enemyColor: '#d946ef',
    enemyBg: 'from-fuchsia-950/90 to-purple-950',
    decorations: ['✨', '🪐', '🌌', '☄️', '🔮'],
  },
};

export function getEraTheme(era: number): EraVisualTheme {
  const boundedEra = Math.max(1, Math.min(10, era));
  return ERA_THEMES[boundedEra] || ERA_THEMES[1];
}
